package internal

// Code generated by gen. Do not edit!
// 代码由 gen 生成。不要手工编辑！

import (
	"zeus/net/demo/proto/test"

	"zeus/net/msgreg"
	"zeus/net/server"
)

func init() {
	// [ServerToClient] 注册发送的消息。需要从类型获取ID。
	msgreg.RegMsg2ID(&test.SayResponse{}, 11002)
}

func RegMsgCreators_hello(svr _IRegMsgCreator) {
	// [ClientToServer] 注册接收的消息。需要从ID创建消息。
	svr.RegMsgCreator(11001, func() server.IMsg { return &test.SayRequest{} })
}
