package server

/*
替换字符串
	SERVER_NAME:
	REG_MSG
	MSG_CREATOR
末尾增加函数
*/

var TMPL_RegMsg = `// Code generated by msgen.
package server

import (
"pb"
"zeus/net/msgreg"
"zeus/net/server"
)

func init() {
	// [ServerToClient] 注册发送的消息。需要从类型获取ID。REG_MSG
}

func RegMsgCreators_SERVER_NAME(svr *Server) {
	// [ClientToServer] 注册接收的消息。需要从ID创建消息。MSG_CREATOR
}
`
