package client

/*
替换字符串
	SERVER_NAME
	REG_MSG
*/
var TMPL_RegMsg = `// Code generated by msgen.
//解析来自SERVER_NAME的消息
package client

import (
	"pb"
	"zeus/net/msgreg"
)

func init() {
	// [ClientToServer] 注册发送的消息。需要从类型获取ID。REG_MSG
}
`
