package client

/*
替换字符
	SERVER_NAME
	CLIENT_IMPORT
*/
var TMPL_Example = `// Code generated by msgen.
// 本文件是对应 SERVER_NAMEMessage 的 MsgProc 实现文件示例。
// 本文件可作为 MsgProc 实现的框架代码。
// 不可以在 generated/client 中实现，因为这样会造成循环导入错误。

package main
import (
	"zeus/net/client"
	"pb"
)

// SERVER_NAMEMessage_MsgProc 是消息处理类.
// 必须实现 ISERVER_NAMEMessage_MsgProc 接口。
// 名字任意，但建议有 MsgProc 后缀。
type SERVER_NAME_MsgProc struct {
	sess client.ISession // 一般都需要包含session对象

	// 可能还应该包含用户和房间对象
	// user *User
	// room *Room
}`
