package internal

// Code generated by gen. Do not edit!
// 代码由 gen 生成。不要手工编辑！

import (
	"zeus/net/client"
)

type _IRegMsgProcFunc interface {
	RegMsgProcFunc(msgID client.MsgID, msgCreator func() client.IMsg, procFunc func(client.IMsg))
}
