package internal

// Code generated by gen. Do not edit!
// 代码由 gen 生成。不要手工编辑！

import (
	"zeus/net/demo/proto/test"

	"zeus/net/msgreg"
)

func init() {
	// [ClientToServer] 注册发送的消息。需要从类型获取ID。
	msgreg.RegMsg2ID(&test.SayRequest{}, 11001)
}
